### ISSUE TITLE
New version requires different settings for Config Persistance

### ISSUE THREAD

**Issue by cmeindl** [timhaak/docker-sabnzbd#11]
Looks like there has been a change to the Config location Mapping
VOLUME ["/datadir", "/download"]
And how the SABNZBD Line parses it -f /datadir/config.ini
The old Docker calls passing in a mapping to the /config/ directory now means running SAB you need to reset your config.

**Comment by neclimdul** [comment]
ugh, yeah this.

**Comment by cmeindl** [comment]
To let you know even when you pass in the new volume name, the config file has a new name the old name (What Sab Creates with no name specified) is sabnzbd.ini

**Comment by timhaak** [comment]
I'm not using the sabnzbd any more so unfortunately don't pick up problems anymore.

**Comment by cmeindl** [comment]
Thanks,

 

You OK for me to fix the config issue I updated the Readme as I thought the change may have been deliberate but it looks like the change in location for the config file was an error Ill update it and put the readme back then anyone who does an update on there existing image wont have to change there config.

 

 

What are you using instead of Sab now.

**Comment by timhaak** [comment]
Thanks. Go for it. I've given you commit access.

I'm using sickrage (Torrents)

**Comment by timhaak** [comment]
https://github.com/timhaak/docker-sickrage

**Comment by cmeindl** [comment]
Thanks.

 

BTW Great docker images across the board use them for my home Cinema System (Manage them with rancher now overkill but makes it easier to update and track)

 

Im in Australia so using torrents given we were a test case for the Dallas Buyers club case im reluctant to use torrents.

 

Just testing the fix for the Config path now ill push and merge shortly.

 

Cam.

**Comment by timhaak** [comment]
:)

Here is South Africa. Rules are slightly different. 

I gather they are problematic that side.

Thanks for the help with fixing

**Comment by cmeindl** [comment]
Fixed with Commit 24b9bcaa92c7246ca93ae1f311ccabcbd2f380d8

**Comment by timhaak** [comment]
Awesome thanks.
