### ISSUE TITLE
Issue with HTTPS for some Newzsites

### ISSUE THREAD

**Issue by cmeindl** [timhaak/docker-sabnzbd#13]
Not an issue with the Docker build but worth noting this version of SABNZBD seems to have overwritten a special setting
enable_https_verification ( off ) 
And set it to on,
This generates the error until you change the switch when downloading
URL Fetching failed; Server uses an untrusted HTTPS certificate

**Comment by grashoper20** [comment]
#16 should fix it.

**Comment by cmeindl** [comment]
Fixed with Merger 45a2e964c918e88f802dd6762bd3206f7e8f747c
Thanks grasshopper20
