### ISSUE TITLE
Short blocks

### ISSUE THREAD

**Issue by sjug** [timhaak/docker-sabnzbd#21]
After downloading anything it gets to the verify stage and fails immediately because of short blocks. It thinks the entire downloaded data is missing, there is no actual data integrity problem with the download. Using 1.10RC3.

I my first guess is it's a UID/GID problem? I don't know why else it would download all the files, then try to verify them and not see any of them?

**Comment by ljdelight** [comment]
I'm a fellow user and haven't seen this problem. Have you tried connecting to the sabnzbd container and create a test directory+file at /incomplete-downloads, move it to /data, then remove it? It's `docker exec -it sabnzbd /bin/sh` to connect.

**Comment by cmeindl** [comment]
Hello do you have a NZB File that shows this behaviour (And also a snapshot of your SABNZB Settings) so  can try and replicate it.

**Comment by sjug** [comment]
Haven't been able to reproduce, thanks for following up @ljdelight and @cmeindl.
