### ISSUE TITLE
1.1 cannot repair

### ISSUE THREAD

**Issue by OverFlow636** [timhaak/docker-sabnzbd#29]
based on the logs par2 is not able to find files to repair. this only started happening since i updated to 1.1, so its probably something to do with the new update

let me know if you would like logs or anything else.

**Comment by cmeindl** [comment]
Hello do you have a NZB File that shows this behaviour (And also a snapshot of your SABNZB Settings) so  can try and replicate it.

**Comment by etwobben** [comment]
I have the same problem, reverting back to older versions of Sab doesn't help. Manually repairing on the commandline does repair any broken files. Every download fails because Sab doesn't match the downloaded par2 with the files.

**Comment by cmeindl** [comment]
Thanks as above  do you have a NZB File that shows this behaviour or a link to its URL  (And also a snapshot of your SABNZB Settings) so can try and replicate it.
Ill try and have a look over the weekend if I have these I can try and replicate what you are seeing

**Comment by etwobben** [comment]
Here is mijn sabnzbd.ini file (removed username/passwords), as with the NZB just pick any, if it has a par2 file it fails always
[sabnzbd.ini.zip](https://github.com/timhaak/docker-sabnzbd/files/502809/sabnzbd.ini.zip)

**Comment by cmeindl** [comment]
Thanks if you could send a link to a NZB File that does fail doesn't matter what it is will make it easier for me, I run this container every day and don't get a lot of failures  so having a nzb File I know fails on your system will make it a lot easier for me to look at this)
Thanks.

**Comment by cmeindl** [comment]
OK I can see some details here,  Looks like this works fine under The Old Base image but doesnt work well under apline, going to need some more work to understand if it is par2cmdline or some other dependency missing 
You can improve the download rate of sab in the interim by setting 
Enable Quick Check to true (This stops par2 checking if all the files are valid)
Ill keep looking and see if I can solve the dependencies

**Comment by cmeindl** [comment]
Found the issue a Bug in the latest version of Par2CmdLine have tested with a rolled back version and it works fine, Ill update and publish the fix in about 20 mIns

**Comment by etwobben** [comment]
That would be great! Thanks for your effort! I'll try the new version when available, and post my findings here.

**Comment by cmeindl** [comment]
Just running several test files through it now, This explains why I have had a few Files fail with corrupt messages it couldnt repair, Hopefully this will be more reliable now, There is also a new Sab RC but I will apply that in a 2nd Releases so I can test them independently.
Ill post a  message when it is up, Do you build yourself or take the image from Dockerhub

**Comment by etwobben** [comment]
I'll build it myself, that's not a problem.

**Comment by cmeindl** [comment]
This should now be fixed with Commit 421aaf9a3faa4176c298888141e737af4bfe4114
Can you pull and test and let me know please.

**Comment by etwobben** [comment]
Just tested it with a download, and it works again! Thanks!

**Comment by cmeindl** [comment]
Cool thanks closing this issue
