### ISSUE TITLE
tcp port getting dropped from iptables

### ISSUE THREAD

**Issue by squiggie** [timhaak/docker-sabnzbd#6]
Each time I have to restart my host, and then subsequently restart my docker images, the ports don't get set back up correctly in iptables for this docker image. I can do a iptables -L -n and see that 9090 and 8080 aren't getting setup. If I manually set them up, sabnzbd works, or if I delete and run the docker image again, it will set them correctly, but if I simply docker start sabnzbd it won't set them.

**Comment by timhaak** [comment]
Hi

How are you running the docker images?

Are you talking about the setting a port mapping with -p of docker ?

If its using the -p option of run with docker then you'll have to follow up with docker as its part of docker.

**Comment by timhaak** [comment]
Just did a test this side with the latest build. Seems to work fine.

Try do a rebuild with the after a git pull or do a docker pull of the image.

**Comment by squiggie** [comment]
I'm not sure what you mean by how am I running the docker image, but I just grabbed your repo, built it, and ran the docker run command with your syntax. So yes, I'm setting up everything with the -p command.

I'm not really sure why it's happening, but it happens every time I reboot. I've deleted everything and rebuilt from scratch and it still happens.

**Comment by timhaak** [comment]
Unfortunately that sounds like a problem on the docker side of things and you'll have to register a bug with them.

Quick explanation of the terminology. Image is what you build or pull down. Once you start running it it's called a container.

Some things to check. Docker doesn't auto start previous running images on reboot (There are ways to do this but not always on by default).

Are you running an Iptables script separately. If so it may be wiping out the rules that docker set. 

If that doesn't help you, as said you'll have to log a bug with Docker.
