### ISSUE TITLE
Sab Listens on localhost Without --server, Overrides Config With --server

### ISSUE THREAD

**Issue by eatnumber1** [timhaak/docker-sabnzbd#8]
So apparently without a config for sab, it will listen on `127.0.0.1` unless you pass the `--server` option to it, which makes for an inaccessible docker container. If you pass `--server`, it will overwrite any values you've changed in the config file for host or port, https or http.

I can see two possible ways to deal with this

1. Document and require users to pass some sort of `--init` flag to initialize the sab configuration.
2. Initialize the configuration ourselves from a modified stored one if the config file is not present.

Personally, I'm leaning towards 2. The only concern would be that of the stored config becoming out-of-date. That concern could be mitigated by making the docker build script generate a new config every time.

What do you think?

**Comment by G-eos** [comment]
Replace in config.ini the line
host = localhost
by
host = 0.0.0.0

**Comment by eatnumber1** [comment]
That would be option three, but we would have to document that users have to do that the first time they run sab.

**Comment by timhaak** [comment]
Or we can have the docker file or start script do it ?

**Comment by timhaak** [comment]
Sorry see no start script. We can do it with the dockerfile.

I'm not really using this image that much but can look and see what can be done this coming weekend.

**Comment by eatnumber1** [comment]
How would we do it with the docker file if not via my method 2?

**Comment by timhaak** [comment]
Sorry this weekend ended up being busy. Was hoping to put some thought into this.

Thinking now though the only way to solve this would be with some startup script.

I know I'm doing this with some of my other images and it seems to work well.

Though would be something along the line of doest the file exist. 

If no create the file allowing access from external.

If the file does exist do nothing.

**Comment by timhaak** [comment]
Closing this for now as current version seems to be working. Happy to accept a pull request if there is a better way.
