### ISSUE TITLE
Remove incompatible themes from dockerfile

### ISSUE THREAD

**Issue by hjr555** [timhaak/docker-sabnzbd#9]
Sab appears to have updated to v1.1.0~rc1.

The existing classic, mobile and plush themes conflict with this version when installing via apt-get, causing the docker build command to fail.
Removing them from the Dockerfile fixes this, and appears to have no adverse effects.

![image](https://cloud.githubusercontent.com/assets/5008913/16876417/b90a9196-4a9b-11e6-9d38-18e84c9398e0.png)

**Comment by timhaak** [comment]
Hi

I've merged your commit.

Let me know if there are any problems. 

Unfortunately don't use this any more so don't pickup when there are problems.
